[build]
  command = "npm install --no-audit --no-fund && npm run lib:build && cd playground && npm install --no-audit --no-fund && npm run build"
  publish = "playground/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"