[build]
  command = "npm run build"        # runs tsup then playground build (from package.json)
  publish = "playground/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"