[build]
  command = "npm run build"
  publish = "playground/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--include=dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"